version: "3"
services:
  broker_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    image: broker_app
    ports:
      - 8081:8000
    volumes:
      - '.:/var/www/html'
    networks:
        - broker
    depends_on:
        - mysql
        - redis
  mysql:
    image: 'mysql:8.0'
    ports:
        - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
          - 'broker_mysql:/var/lib/mysql'
    networks:
        - broker
    healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
        retries: 3
        timeout: 5s
  redis:
      image: 'redis:alpine'
      ports:
        - '${FORWARD_REDIS_PORT:-6379}:6379'
      volumes:
        - 'broker_redis:/data'
      networks:
        - broker
      healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        retries: 3
        timeout: 5s
networks:
  broker:
    driver: bridge
volumes:
  broker_mysql:
    driver: local
  broker_redis:
    driver: local
